config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|ru/ do
  root "chapter3#home"

  get "/home", to: "chapter3#home"
  resources :users
  resources :account_activations, only: :edit
  resources :password_resets, except: %i(show index destroy)
  resources :microposts, only: %i(create destroy)
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :load_user, :valid_user, :check_expiration, only: %i(edit update)

  def new; end

  def edit; end

  def create
    @user = User.find_by email: params[:password_reset][:email].downcase
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = t "forget.success"
      redirect_to root_path
    else
      flash.now[:danger] = t "forget.fail"
      render :new
    end
  end

  def update
    if params[:user][:password].blank?
      @user.errors.add :password, t("forget.reset.error")
      render :edit
    elsif @user.update user_params
      log_in @user
      @user.update_attribute :reset_digest, nil
      flash[:success] = t "forget.reset.success"
      redirect_to @user
    else
      flash.now[:warning] = t "forget.reset.fail"
      render :edit
    end
  end

  private

  def load_user
    @user = User.find_by email: params[:email]
    return if @user.present?

    flash[:warning] = t "user.new.absent"
    redirect_to root_path
  end

  def valid_user
    return if @user && @user.authenticated?(:reset, params[:id])

    flash[:warning] = t "user.new.absent"
    redirect_to root_path
  end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<% provide :title, "Reset password" %>

<h1>Reset password</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user, url: password_reset_path(params[:id]) do |f| %>
    <%= render "shared/error_messages" %>
    <%= hidden_field_tag :email, @user.email %>
    <%= f.label :password, t("forget.reset.passwordlabel") %>
    <%= f.password_field :password, class: "form-control" %>
    <%= f.label :password_confirmation, t("forget.reset.confirmation") %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
    <%= f.submit "Update password", class: "btn btn-primary" %>
  <% end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<h1>PasswordResets#new</h1>
<% provide :title, "forget.title" %>
<h1>Forgot password</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for :password_reset, url: password_resets_path do |f| %>
    <%= f.label :email, t("forget.email") %>
    <%= f.email_field :email, class: "form-control" %>
    <%= f.submit "Submit", class: "btn btn-primary" %>
  <% end %>
  </div>
</div>