config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|ru/ do
  root "chapter3#home"

  get "/home", to: "chapter3#home"
  resources :users
  resources :account_activations, only: :edit
  resources :password_resets, except: %i(show index destroy)
  resources :microposts, only: %i(create destroy)
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
end

app/views/layouts/_header.html.erb
<html>
  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <%= link_to "sample app", "#", id: "logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
          <% if logged_in? %>
            <li><%= link_to "User", users_path %></li>
            <li class="dropdown">
            <%= link_to "#", {class: "dropdown-toggle", data: {"toggle" => "dropdown"}} do %>
              <%= "account" %>
              <b class="caret"></b>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", users_path %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to "Log Out", logout_path, method: :delete %></li>
            </ul>
            </li>
          <% else %>
            <li><%= link_to t("login.title"), login_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
  <%= render "layouts/header" %>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>